# Generated by Django 3.2.3 on 2021-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Ongoing Events', 'Ongoing Events'), ('Events Conducted', 'Events Conducted'), ('Upcoming Events', 'Upcoming Events')], max_length=200, null=True),
        ),
    ]
