# Generated by Django 3.2.3 on 2021-05-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstatus',
            name='events_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
