# Generated by Django 3.2.3 on 2021-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Ongoing Events', 'Ongoing Events'), ('Events Conducted', 'Events Conducted'), ('Upcoming Events', 'Upcoming Events'), ('Completed Events', 'Completed Events')], max_length=200, null=True),
        ),
    ]
