# Generated by Django 3.2.3 on 2021-05-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200, null=True)),
                ('limit', models.IntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('banner', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(choices=[('Ongoing Events', 'Ongoing Events'), ('Events Completed', 'Events Completed'), ('Upcoming Events', 'Upcoming Events')], max_length=200, null=True),
        ),
    ]
