# Generated by Django 3.2.3 on 2021-05-22 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210520_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventstatus',
            name='events_created',
        ),
        migrations.DeleteModel(
            name='NewEvent',
        ),
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
