# Generated by Django 3.2.3 on 2021-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210523_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='register',
            field=models.BooleanField(null=True),
        ),
    ]
